title: Machine Learning Summer School Deadlines
description: Countdowns to Machine Learning Summer School deadlines
author: Shashank Shekhar

domain: "aideadlin.es"
baseurl: ""

twitter_hashtag: machinelearning
github_username: sshkhr
github_repo: awesome-mlss

markdown: kramdown
ga_id:

include: ['_pages']
