title: "Machine Learning Summer School Guide"
tagline: "Awesome MLSS"
description: "Find machine learning and artificial intelligence summer schools worldwide by topics, locations, dates, and deadlines. Natural Language Processing, Computer Vision, Reinforcement Learning, and more."
url: "https://awesome-mlss.com"   # Full URL to your site, important for absolute image URLs in meta tags
author: "awesome-mlss"

domain: "awesome-mlss.com"
baseurl: ""

# Twitter settings for jekyll-seo-tag
twitter:
  username: "awesomeMLSS"
  card: "summary_large_image"  # or "summary" if you prefer smaller cards

# Social profiles for jekyll-seo-tag
social:
  name: "Awesome MLSS"
  links:
    - "https://twitter.com/awesomeMLSS"
    - "https://github.com/awesome-mlss"
    - "https://www.linkedin.com/company/awesome-mlss"

github_username: awesome-mlss
github_repo: awesome-mlss

markdown: kramdown
ga_id:

logo: "/static/img/favicon.png"
locale: "en_US"

include: ['_pages']

plugins:
  - jekyll-datapage-generator
  - jekyll-seo-tag
  - jekyll-maps
  - jekyll-sitemap
  - jekyll-feed

# Datapage_gen configuration
page_gen:
  # Each entry in `_data/summerschools.yml` will create a page
    - data: "summerschools"       # The name of your data file (without extension)
      template: "summerschool"    # The template file (without extension) to use
      name: "id"               # The output filename
      dir: "summerschool"         # The output directory
      extension: "html"           # optional, defaults to html
  # Each entry in `_data/archive.yml` will create a page in archives
    - data: "archive"       # The name of your data file (without extension)
      template: "archivesummerschool"    # The template file (without extension) to use
      name: "id"               # The output filename
      dir: "archivesummerschool"         # The output directory
      extension: "html"           # optional, defaults to html
  # Each entry in `_data/recurringschools.yml` will create a page in recurringschools
    - data: "recurringschools"       # The name of your data file (without extension)
      template: "recurringschool"    # The template file (without extension) to use
      name: "slug"               # The output filename
      dir: "recurringschool"         # The output directory
      extension: "html"           # optional, defaults to html

# Map configuration
maps:
  google:
    api_key: AIzaSyDpiWMzw3q9nBtQK4ZB7fskqPPiHbCmhvI
    marker_cluster:
      enabled: false

# Feed configuration
feed:
  icon: /static/img/favicon.png
  logo: /static/img/favicon.png