name: Update README

on:
  push:
    paths:
      - 'site/_data/summerschools.yml'
  pull_request:
    paths:
      - 'site/_data/summerschools.yml'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pyyaml
          pip install python-dateutil

      - name: Update README
        run: |
          python scripts/update_readme.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: auto-update README with latest summer schools"
          git push
